### ISSUE TITLE
Emmet does not work after set the file as Jinja-HTML mode.

### ISSUE THREAD

**Issue by wnbotoo** [wholroyd/vscode-jinja#1]
As the title said.

**Comment by wholroyd** [comment]
I don't see Emmet being available for vscode unless it was from a third party. Are you using the `vscode-twig-pack` extension? (https://github.com/Bajdzis/vscode-twig-pack)

**Comment by wholroyd** [comment]
Nevermind, it looks like it's part of vscode itself now. I'll look into it.

**Comment by wholroyd** [comment]
It appears that Emmet functionality only works in certain languages, which is defined in the editor core (https://github.com/Microsoft/vscode/blob/6e5a331ac701fc9028aac577a4b188686fc9330a/src/vs/workbench/parts/emmet/node/editorAccessor.ts#L22). I pushed a new version to the marketplace that attempts to override HTML with both Jinja and HTML language support. So now you should be able to have all the the HTML functionality without losing the Jinja support.

After you upgrade to 0.0.4 and switch to HTML, it may still show Jinja in the language identifier, but the functionality should now work.

**Comment by wholroyd** [comment]
Changes were in https://github.com/wholroyd/vscode-jinja/commit/63cea8276a4462422d1037cb9e9d3a6994e30fd4.

**Comment by wnbotoo** [comment]
Sorry for late reply.  I have upgraded 0.04, it works. Thank you.
