### ISSUE TITLE
Jinja attempts to parse .j2 files as .yaml files

### ISSUE THREAD

**Issue by ebmarquez** [wholroyd/vscode-jinja#13]
Jinja systax is not being parse correctly.  Throwing errors for plain text in the body.
When viewing the file as a diff using vs code, the text is parse correctly.
VS Code: 1.12.0-insider

Open File
![screenshot 3](https://cloud.githubusercontent.com/assets/15785107/25387441/b4f57c4c-297f-11e7-926b-e8ecce3a2ab2.png)

View as Diff

![screenshot 4](https://cloud.githubusercontent.com/assets/15785107/25387566/23b7d3a0-2980-11e7-979a-051166808732.png)

**Comment by wholroyd** [comment]
I'll take a look to see what I can do, but it might be a while before I can get a fix in. Thanks for reporting the issue!

**Comment by wholroyd** [comment]
This should be fixed with the latest version.
