### ISSUE TITLE
Disable code formatting

### ISSUE THREAD

**Issue by jsnjack** [wholroyd/vscode-jinja#2]
If I have following code in the editor:

```
{% if something %}
    {% if nothing %}
        <a>A</a>
    {% endif %}
{% endif %}
```

and I save the file, it reformats it to:

```
{% if something %} {% if nothing %}
<a>A</a> {% endif %} {% endif %}
```

**Comment by jsnjack** [comment]
I also use this extension https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter . I think, for some reason it treats jinja template as html file

**Comment by wholroyd** [comment]
The extension I made only provides colorization of the Jinja templating components. It does inherit from the HTML language as to provide support for Jinja when used with HTML, so other extensions can affect the same document. If anything is reformatting the file, it's not from my extension.

It does appear that the extension you mentioned does attempt to format the file when saving. There is a method defined in that project's README to disable that feature if it's causing problems. It appears the feature is relatively new as well, only about a month old - https://github.com/Lonefy/vscode-JS-CSS-HTML-formatter/issues/4

**Comment by jsnjack** [comment]
Thank you! I already disabled formatting on save, but it would probably be nice to have it for js and html files (jinja files should be left intact). I will create an issue in the formatter repository

**Comment by linanwx** [comment]
After install JS-CSS-HTML Formatter, you should edit this line in formatter.json.
    `"onSave": true,` -->     `"onSave": false,`
