### ISSUE TITLE
Extension deprecated?

### ISSUE THREAD

**Issue by isidorn** [wholroyd/vscode-jinja#37]
Isidor here from the VS Code team 👋 

We have noticed that you have not updated your extension for quite some time.
Do you plan to continue working on your extension? Do you feel like it is feature complete? Or is it deprecated? 
 
We currently support deprecated extensions and we could mark your extension as deprecated. What do you think about that option? 

Thank you @wholroyd

**Comment by wholroyd** [comment]
I responded in https://github.com/microsoft/vscode/issues/150743.

**Comment by isidorn** [comment]
Not deprecated based on response, let's close this as a no-op
