### ISSUE TITLE
No more HTML support after installing Jinja extension!

### ISSUE THREAD

**Issue by ghost** [wholroyd/vscode-jinja#8]
Hi

Does anybody know why there is no HTML support in Visual Studio Code after installing the Jinja extension? I am using the version 1.7.1 on Mac and if I save the file as .html the editor tells me in the "select language mode" option that Jinja is used as language.

There is no html tag highlighting and if I try to select html as language the editor doesn't show it no more as an option! See screenshot:

<img width="1022" alt="screen shot 2016-11-03 at 19 59 10" src="https://cloud.githubusercontent.com/assets/23245678/19982088/eb502df8-a204-11e6-91c1-d0308093c3e7.png">

After uninstalling the Jinja extension, the editor tells me that HTML language is YAML, because HTML support is gone forever! 

Best regards

**Comment by wholroyd** [comment]
The HTML language is built into Code, so there is no way of removing the language support even if installing my plugin. There was another issue logged about HTML coloring being lost for some reason, but it was working. It was most likely a change in Code that caused this.

**Comment by wholroyd** [comment]
It looks like in a recent version of VSCode, there was a change to embedded and injected languages, which makes this behavior occur. This didn't use to happen. The support is still there in the editor, it's just hidden. The workaround is to uninstall my extension until I can get an update out in the next couple of days. I think I have a solution, but want to test it some more.

**Comment by OliverJAsh** [comment]
Any ideas what is causing this?

**Comment by atombender** [comment]
Any update here? I can't install this extension because of this issue.

**Comment by Silvenga** [comment]
That pull request should fix it, would it be possible to verify @atombender?

**Comment by atombender** [comment]
I can test if it you tell me how I can install the patched extension.

**Comment by Silvenga** [comment]
@atombender sweet! VSCode made it easily, steps to debug below:

- Clone Repo my pull request (https://github.com/Silvenga/vscode-jinja)
- Open folder with VSCode
- Press F5
  - The new VSCode instance will create a "temporary profile" overriding the extension
- Open stuff and test

**Comment by atombender** [comment]
Can confirm that HTML highlighting and autocompletion is back.

**Comment by wholroyd** [comment]
Published 0.0.8 to the marketplace with these changes. :)
